"""Provider-neutral market-data capability contracts."""

from .aggregate_contract import (
    AggregateContractError,
    MarketAggregateResult,
    fetch_official_market_aggregates,
    parse_tpex_market_aggregate,
    parse_twse_market_aggregate,
)
from .exchange import (
    TPEX_DAILY_ADAPTER_VERSION,
    TPEX_DAILY_SOURCE_CODE,
    TWSE_DAILY_ADAPTER_VERSION,
    TWSE_DAILY_SOURCE_CODE,
    TpexOfficialDailyProvider,
    TwseOfficialDailyProvider,
)
from .history import (
    HistoricalBar,
    HistoricalFetchResult,
    HistoricalProviderError,
    HistoryAvailability,
    YahooChartHistoricalProvider,
    probe_history_availability,
)
from .index_contract import (
    IndexContractError,
    IndexDataStatus,
    MarketIndexResult,
    TpexIndexCrossCheck,
    fetch_official_market_indexes,
    parse_tpex_index_crosscheck,
    parse_tpex_market_index,
    parse_twse_market_index,
    unavailable_market_index,
)
from .ingestion import (
    HistoricalIngestionError,
    HistoricalIngestionResult,
    HistoricalSourceRegistration,
    ingest_historical,
)
from .institutional_flow_contract import (
    INSTITUTIONAL_FLOW_ADAPTER_VERSION,
    TPEX_INSTITUTIONAL_FLOW_ENDPOINT,
    TPEX_INSTITUTIONAL_FLOW_SOURCE,
    TWSE_INSTITUTIONAL_FLOW_ENDPOINT,
    TWSE_INSTITUTIONAL_FLOW_SOURCE,
    InstitutionalFlowContractError,
    MarketInstitutionalFlowResult,
    fetch_official_market_institutional_flows,
    parse_tpex_institutional_flow,
    parse_twse_institutional_flow,
    persist_market_institutional_flows,
)
from .taishin import (
    TaishinHistoryClient,
    TaishinIntradayClient,
    TaishinIntradayProvider,
    TaishinTechnicalAnalysisProvider,
)
from .yahoo_quote import (
    YAHOO_QUOTE_ADAPTER_VERSION,
    YAHOO_QUOTE_SOURCE_CODE,
    YahooQuoteProvider,
)

__all__ = [
    "INSTITUTIONAL_FLOW_ADAPTER_VERSION",
    "TPEX_DAILY_ADAPTER_VERSION",
    "TPEX_DAILY_SOURCE_CODE",
    "TPEX_INSTITUTIONAL_FLOW_ENDPOINT",
    "TPEX_INSTITUTIONAL_FLOW_SOURCE",
    "TWSE_DAILY_ADAPTER_VERSION",
    "TWSE_DAILY_SOURCE_CODE",
    "TWSE_INSTITUTIONAL_FLOW_ENDPOINT",
    "TWSE_INSTITUTIONAL_FLOW_SOURCE",
    "YAHOO_QUOTE_ADAPTER_VERSION",
    "YAHOO_QUOTE_SOURCE_CODE",
    "AggregateContractError",
    "HistoricalBar",
    "HistoricalFetchResult",
    "HistoricalIngestionError",
    "HistoricalIngestionResult",
    "HistoricalProviderError",
    "HistoricalSourceRegistration",
    "HistoryAvailability",
    "IndexContractError",
    "IndexDataStatus",
    "InstitutionalFlowContractError",
    "MarketAggregateResult",
    "MarketIndexResult",
    "MarketInstitutionalFlowResult",
    "TaishinHistoryClient",
    "TaishinIntradayClient",
    "TaishinIntradayProvider",
    "TaishinTechnicalAnalysisProvider",
    "TpexIndexCrossCheck",
    "TpexOfficialDailyProvider",
    "TwseOfficialDailyProvider",
    "YahooChartHistoricalProvider",
    "YahooQuoteProvider",
    "fetch_official_market_aggregates",
    "fetch_official_market_indexes",
    "fetch_official_market_institutional_flows",
    "ingest_historical",
    "parse_tpex_index_crosscheck",
    "parse_tpex_institutional_flow",
    "parse_tpex_market_aggregate",
    "parse_tpex_market_index",
    "parse_twse_institutional_flow",
    "parse_twse_market_aggregate",
    "parse_twse_market_index",
    "persist_market_institutional_flows",
    "probe_history_availability",
    "unavailable_market_index",
]
