"use client";
import { useEffect, useMemo, useState } from "react";
import { AppShell, Card, DataState, EmptyState, Freshness, PageContainer } from "./V2Foundation";
import { StockEncyclopediaDrawer, type StockDrawerItem } from "./StockEncyclopediaDrawer";
import { useSnapshot } from "../../lib/snapshot-store";
import type { StockView } from "../../lib/types";
type SortKey = "change" | "price" | "volume";
const isLive = (s: StockView) => /CURRENT|LIVE/i.test(s.dataFreshness ?? "");
const price = (v: number | null) => v === null ? "—" : v.toLocaleString("zh-TW", { maximumFractionDigits: 2 });
const change = (s: StockView) => s.change === null ? "—" : `${s.change >= 0 ? "+" : ""}${s.change.toFixed(2)}%`;
const roleLabel = (value: string | null) => { const v = (value ?? "").trim().toUpperCase(); if (["代表股", "PRIMARY", "REPRESENTATIVE", "LEADER"].includes(v)) return "代表股"; if (["核心股", "CORE", "SECONDARY"].includes(v)) return "核心股"; if (["關聯股", "RELATED"].includes(v)) return "關聯股"; return null; };
export default function StockExplorerPage() {
  const { bundle, status } = useSnapshot(); const [market, setMarket] = useState("all"); const [sort, setSort] = useState<SortKey>("change"); const [mode, setMode] = useState("all"); const [topic, setTopic] = useState(""); const [advancedOpen, setAdvancedOpen] = useState(false); const [selected, setSelected] = useState<StockView | null>(null); const [lastSorted, setLastSorted] = useState(() => new Date());
  const topics = useMemo(() => [...new Set(bundle.topics.map((item) => item.name).filter(Boolean))].sort((a, b) => a.localeCompare(b, "zh-Hant")), [bundle.topics]);
  const rows = useMemo(() => { const filtered = bundle.stockUniverse.filter((s) => (market === "all" || s.relations.some((r) => r.type === market)) && (mode === "all" || (mode === "live" ? isLive(s) : !isLive(s))) && (!topic || s.topicNames.includes(topic) || s.relations.some((r) => r.topic === topic))); return filtered.sort((a, b) => sort === "price" ? (b.price ?? -Infinity) - (a.price ?? -Infinity) : sort === "volume" ? (b.volume ?? -Infinity) - (a.volume ?? -Infinity) : (b.change ?? -Infinity) - (a.change ?? -Infinity)); }, [bundle.stockUniverse, market, mode, sort, topic]);
  useEffect(() => { const handler = (event: KeyboardEvent) => { if (event.key === "Escape" && selected) setSelected(null); }; document.addEventListener("keydown", handler); return () => document.removeEventListener("keydown", handler); }, [selected]);
  const drawerItem = (stock: StockView): StockDrawerItem => { const main = bundle.topics.find((item) => item.name === stock.topicMain); return { code: stock.code, name: stock.name ?? "未提供名稱", price: stock.price, changePct: stock.change, dataFreshness: stock.dataFreshness, updatedAt: stock.updatedAt, dataDate: stock.dataDate, isPreview: bundle.source !== "snapshot", topics: stock.relations.map((r) => ({ name: r.topic, role: roleLabel(r.role) })), mainTopic: stock.topicMain ? { name: stock.topicMain, grade: main?.grade ?? null, state: main?.strengthState ?? null } : null }; };
  const drawer = selected && <StockEncyclopediaDrawer presentation="inline" stock={drawerItem(selected)} onClose={() => setSelected(null)} />;
  return <AppShell currentPath="/stocks"><PageContainer eyebrow="股票資料庫" title="股票" description="市場圖鑑：瀏覽完整股票資料庫，從市場身份開始理解個股。"><div className="tp-stock-meta"><Freshness state="盤中更新" asOf={bundle.qualityPanelData.freshness.dataDate ?? "資料日期待補"} /><DataState state={bundle.source === "snapshot" && status.state !== "error" ? "AVAILABLE" : "UNAVAILABLE"} />{bundle.source !== "snapshot" && <span className="tp-preview-badge">Preview · 部分資料等待正式 Read Model</span>}</div><section className="tp-stock-workspace"><div className="tp-stock-main"><Card className="tp-stock-toolbar"><label>市場<select value={market} onChange={(e) => setMarket(e.target.value)}><option value="all">全部</option><option value="上市" disabled>上市（正式欄位待補）</option><option value="上櫃" disabled>上櫃（正式欄位待補）</option></select></label><label>排序<select value={sort} onChange={(e) => { setSort(e.target.value as SortKey); setLastSorted(new Date()); }}><option value="change">漲幅</option><option value="price">股價</option><option value="volume">成交量</option></select></label><button type="button" className={`tp-stock-advanced-toggle ${advancedOpen ? "is-open" : ""}`} aria-expanded={advancedOpen} onClick={() => setAdvancedOpen((v) => !v)}>進階篩選⌄</button><button type="button" className="tp-stock-resort" onClick={() => setLastSorted(new Date())}>↻ 重新排序</button></Card>{advancedOpen && <Card className="tp-stock-advanced"><label>題材<select value={topic} onChange={(e) => setTopic(e.target.value)}><option value="">全部題材</option>{topics.map((item) => <option key={item} value={item}>{item}</option>)}</select></label><span>均線</span><span>法人</span><span>技術</span><span>更新狀態</span><span className="tp-muted">題材清單來自正式 Topic read model。</span></Card>}<div className="tp-stock-segments"><button className={mode === "all" ? "is-active" : ""} onClick={() => setMode("all")}>全部</button><button className={mode === "live" ? "is-active" : ""} onClick={() => setMode("live")}>LIVE</button><button className={mode === "eod" ? "is-active" : ""} onClick={() => setMode("eod")}>EOD</button><span className="tp-muted">最後排序 {lastSorted.toLocaleTimeString("zh-TW", { hour: "2-digit", minute: "2-digit" })} · {rows.length} 檔</span></div>{bundle.source !== "snapshot" ? <Card><EmptyState title="股票資料尚未載入" description="目前無法取得正式 snapshot，列表不會用示範資料補值。" /></Card> : <div className="tp-stock-grid">{rows.map((stock) => <button type="button" className={`tp-stock-tile ${selected?.code === stock.code ? "is-selected" : ""}`} key={stock.code} onClick={() => setSelected(stock)}><span className="tp-stock-tile-top"><strong>{stock.name ?? "未提供名稱"}</strong><em>{isLive(stock) ? "LIVE" : "EOD"}</em></span><small>{stock.code} · {stock.topicMain ?? "題材待補"}</small><span className="tp-stock-tile-quote"><b>{price(stock.price)}</b><i className={stock.change !== null && stock.change < 0 ? "tp-stock-down" : "tp-stock-up"}>{change(stock)}</i></span>{!isLive(stock) && <span className="tp-stock-eod-note">盤後更新</span>}</button>)}</div>}</div>{drawer}</section></PageContainer></AppShell>;
}
