"use client";
import { useEffect, useMemo, useState } from "react";
import { X } from "lucide-react";
import { AppShell, Button, Card, DataState, EmptyState, FavoriteStar, Freshness, PageContainer, RoleChip } from "./V2Foundation";
import { useSnapshot } from "../../lib/snapshot-store";
import type { StockView } from "../../lib/types";
type SortKey = "change" | "price" | "volume";
const live = (s: StockView) => /CURRENT|LIVE/i.test(s.dataFreshness ?? "");
const role = (s: StockView) => s.relations.find((r) => r.role)?.role ?? null;
const price = (v: number | null) => v == null ? "Data pending" : v.toLocaleString("zh-TW", { maximumFractionDigits: 2 });
const change = (s: StockView) => s.change == null ? "Data pending" : `${s.change >= 0 ? "+" : ""}${s.change.toFixed(2)}%`;
export default function StockExplorerPage() {
  const { bundle, status } = useSnapshot();
  const [market, setMarket] = useState("all"); const [sort, setSort] = useState<SortKey>("change"); const [mode, setMode] = useState("all"); const [advancedOpen, setAdvancedOpen] = useState(false); const [selected, setSelected] = useState<StockView | null>(null); const [lastSorted, setLastSorted] = useState(() => new Date());
  const rows = useMemo(() => { const filtered = bundle.stockUniverse.filter((s) => (market === "all" || s.relations.some((r) => r.type === market)) && (mode === "all" || (mode === "live" ? live(s) : !live(s)))); return filtered.sort((a, b) => sort === "price" ? (b.price ?? -Infinity) - (a.price ?? -Infinity) : sort === "volume" ? (b.volume ?? -Infinity) - (a.volume ?? -Infinity) : (b.change ?? -Infinity) - (a.change ?? -Infinity)); }, [bundle.stockUniverse, market, mode, sort]);
  useEffect(() => { const handler = (event: KeyboardEvent) => { if (event.key === "Escape" && selected) setSelected(null); }; document.addEventListener("keydown", handler); return () => document.removeEventListener("keydown", handler); }, [selected]);
  const drawer = selected && <aside className="tp-stock-drawer" aria-label="Stock Encyclopedia"><header className="tp-stock-drawer-head"><div><p className="tp-eyebrow">Stock Encyclopedia</p><h2>{selected.name ?? "Unnamed stock"}</h2><p className="tp-muted">{selected.code} · {selected.topicMain ?? "Industry pending"}</p></div><div className="tp-stock-drawer-actions"><FavoriteStar /><button className="tp-stock-close" aria-label="Close stock drawer" title="Close" onClick={() => setSelected(null)}><X size={18} /></button></div></header><div className="tp-stock-status-row"><DataState state={live(selected) ? "盤中更新" : "盤後更新"} /><span className="tp-muted">{selected.updatedAt ?? selected.dataDate ?? "As-of pending"}</span></div><div className="tp-stock-drawer-price"><span>{price(selected.price)}</span><b className={selected.change != null && selected.change < 0 ? "tp-stock-down" : "tp-stock-up"}>{change(selected)}</b></div><dl className="tp-stock-facts"><div><dt>Role</dt><dd>{role(selected) ? <RoleChip>{role(selected)}</RoleChip> : "Data pending"}</dd></div><div><dt>Topics</dt><dd>{selected.topicNames.length ? selected.topicNames.map((name) => <RoleChip key={name}>{name}</RoleChip>) : "Data pending"}</dd></div><div><dt>Freshness</dt><dd>{live(selected) ? "Included in intraday tracking." : "Below 60MA; updated after close."}</dd></div></dl><Button variant="secondary">View opportunity →</Button></aside>;
  return <AppShell currentPath="/stocks"><PageContainer eyebrow="Stock database" title="Stocks" description="Market Encyclopedia: browse the full stock database and understand each stock's current identity."><div className="tp-stock-meta"><Freshness state="盤中更新" asOf={bundle.qualityPanelData.freshness.dataDate ?? "As-of pending"} /><DataState state={bundle.source === "snapshot" && status.state !== "error" ? "AVAILABLE" : "UNAVAILABLE"} /></div><section className="tp-stock-workspace"><div className="tp-stock-main"><Card className="tp-stock-toolbar"><label>Market<select value={market} onChange={(e) => setMarket(e.target.value)}><option value="all">All</option><option value="上市">Listed</option><option value="上櫃">OTC</option></select></label><label>Sort<select value={sort} onChange={(e) => { setSort(e.target.value as SortKey); setLastSorted(new Date()); }}><option value="change">Change</option><option value="price">Price</option><option value="volume">Volume</option></select></label><button type="button" className={`tp-stock-advanced-toggle ${advancedOpen ? "is-open" : ""}`} aria-expanded={advancedOpen} onClick={() => setAdvancedOpen((v) => !v)}>Advanced filters⌄</button><button type="button" className="tp-stock-resort" onClick={() => setLastSorted(new Date())}>↻ Re-sort</button></Card>{advancedOpen && <Card className="tp-stock-advanced"><span>Topics</span><span>Moving averages</span><span>Institutions</span><span>Technical</span><span>Freshness</span><span className="tp-muted">Uses existing screener fields.</span></Card>}<div className="tp-stock-segments"><button className={mode === "all" ? "is-active" : ""} onClick={() => setMode("all")}>All</button><button className={mode === "live" ? "is-active" : ""} onClick={() => setMode("live")}>LIVE</button><button className={mode === "eod" ? "is-active" : ""} onClick={() => setMode("eod")}>EOD</button><span className="tp-muted">Last sorted {lastSorted.toLocaleTimeString("en-US", { hour: "2-digit", minute: "2-digit" })} · {rows.length} stocks</span></div>{bundle.source !== "snapshot" ? <Card><EmptyState title="Stock data unavailable" description="The formal snapshot is not available; no demo values are substituted." /></Card> : <div className="tp-stock-grid">{rows.map((stock) => <button type="button" className={`tp-stock-tile ${selected?.code === stock.code ? "is-selected" : ""}`} key={stock.code} onClick={() => setSelected(stock)}><span className="tp-stock-tile-top"><strong>{stock.name ?? "Unnamed stock"}</strong><em>{live(stock) ? "LIVE" : "EOD"}</em></span><small>{stock.code} · {stock.topicMain ?? "Topic pending"}</small><span className="tp-stock-tile-quote"><b>{price(stock.price)}</b><i className={stock.change != null && stock.change < 0 ? "tp-stock-down" : "tp-stock-up"}>{change(stock)}</i></span>{!live(stock) && <span className="tp-stock-eod-note">Post-close update</span>}</button>)}</div>}</div>{drawer}</section></PageContainer></AppShell>;
}
