/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/admin/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Dashboard */
        get: operations["dashboard_api_v1_admin_dashboard_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/imports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Imports */
        get: operations["imports_api_v1_admin_imports_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/imports/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Import Detail */
        get: operations["import_detail_api_v1_admin_imports__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/instruments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Instruments */
        get: operations["instruments_api_v1_admin_instruments_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/instruments/{instrument_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Instrument Detail */
        get: operations["instrument_detail_api_v1_admin_instruments__instrument_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/markets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Markets */
        get: operations["markets_api_v1_admin_markets_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/relations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Relations */
        get: operations["relations_api_v1_admin_relations_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/schema": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Schema */
        get: operations["schema_api_v1_admin_schema_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/topics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Topics */
        get: operations["topics_api_v1_admin_topics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/topics/{topic_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Topic Detail */
        get: operations["topic_detail_api_v1_admin_topics__topic_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analytics/strategy-performance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Performance */
        get: operations["performance_api_v1_analytics_strategy_performance_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analytics/topic-rotation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Rotation */
        get: operations["rotation_api_v1_analytics_topic_rotation_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/meta/data-status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Api Data Status */
        get: operations["api_data_status_api_v1_meta_data_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/operations/live/configuration": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Configuration */
        get: operations["configuration_api_v1_operations_live_configuration_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/operations/live/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Status */
        get: operations["status_api_v1_operations_live_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/operations/live/tracking": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Tracking */
        get: operations["tracking_api_v1_operations_live_tracking_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/opportunities/shadow": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read deterministic shadow Opportunity projections */
        get: operations["list_shadow_opportunities_api_v1_opportunities_shadow_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/opportunities/shadow/{opportunity_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read one shadow Opportunity detail projection */
        get: operations["shadow_opportunity_detail_api_v1_opportunities_shadow__opportunity_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/recommendations/latest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Latest Recommendations */
        get: operations["latest_recommendations_api_v1_recommendations_latest_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/snapshot/latest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Snapshot Latest */
        get: operations["snapshot_latest_api_v1_snapshot_latest_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stocks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stocks */
        get: operations["stocks_api_v1_stocks_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stocks/{code}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stock */
        get: operations["stock_api_v1_stocks__code__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stocks/{code}/price-history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stock Price History */
        get: operations["stock_price_history_api_v1_stocks__code__price_history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stocks/{instrument_id}/opportunities/shadow": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read a stock-oriented shadow Opportunity projection */
        get: operations["stock_shadow_opportunities_api_v1_stocks__instrument_id__opportunities_shadow_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/strategies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Strategies */
        get: operations["strategies_api_v1_strategies_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/strategies/{key}/candidates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Candidates */
        get: operations["candidates_api_v1_strategies__key__candidates_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/topic-intelligence/latest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Latest Topic Intelligence */
        get: operations["latest_topic_intelligence_api_v1_topic_intelligence_latest_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/topics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Topics */
        get: operations["topics_api_v1_topics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/topics/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Topic */
        get: operations["topic_api_v1_topics__slug__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/topics/{topic_id}/opportunities/shadow": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read a topic-oriented shadow Opportunity projection */
        get: operations["topic_shadow_opportunities_api_v1_topics__topic_id__opportunities_shadow_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/home": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Home */
        get: operations["home_api_v2_home_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/stocks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read the formal TPE/TWO stock universe */
        get: operations["stocks_api_v2_stocks_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/stocks/{symbol}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read one formal stock */
        get: operations["stock_api_v2_stocks__symbol__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/topic-snapshots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read V2 topic snapshots by date or history */
        get: operations["list_topic_snapshots_api_v2_topic_snapshots_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/topics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read the formal topic read model */
        get: operations["topics_api_v2_topics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/topics/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read one formal topic */
        get: operations["topic_api_v2_topics__slug__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Healthz */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Readyz */
        get: operations["readyz_readyz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** CandidateResponse */
        CandidateResponse: {
            /** Code */
            code: string;
            /**
             * Datadate
             * Format: date
             */
            dataDate: string;
            /** Invalidationprice */
            invalidationPrice: number | null;
            /** Modelversion */
            modelVersion: string;
            /** Name */
            name: string;
            /** Price */
            price: number | null;
            /** Rank */
            rank: number;
            /** Reason */
            reason: string | null;
            /** Score */
            score: number | null;
            /** Selected */
            selected: boolean;
            /** Strategykey */
            strategyKey: string;
            /** Supportprice */
            supportPrice: number | null;
            /** Triggerprice */
            triggerPrice: number | null;
        };
        /** Constituent */
        Constituent: {
            /** Code */
            code: string;
            /** Name */
            name: string;
            /** Relationtype */
            relationType: string;
            /** Weight */
            weight: number | null;
        };
        /** DataStatus */
        DataStatus: {
            /** Agedays */
            ageDays: number;
            /** Bundlehash */
            bundleHash: string;
            /** Bundleversion */
            bundleVersion: string;
            /** Classification */
            classification: string;
            /**
             * Completedat
             * Format: date-time
             */
            completedAt: string;
            /** Contractversion */
            contractVersion: string;
            /**
             * Datadate
             * Format: date
             */
            dataDate: string;
            /** Freshness */
            freshness: string;
            /**
             * Generatedat
             * Format: date-time
             */
            generatedAt: string;
            /** Rowcounts */
            rowCounts: {
                [key: string]: number;
            };
            /** Sourcekind */
            sourceKind: string;
            /** Sourcename */
            sourceName: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Status */
            status: string;
        };
        /** HistoricalPriceHistoryResponse */
        HistoricalPriceHistoryResponse: {
            /** Availabilityreason */
            availabilityReason: string | null;
            /** Code */
            code: string;
            /** Items */
            items: components["schemas"]["HistoricalPricePoint"][];
            /** Market */
            market: string;
            /** Pointcount */
            pointCount: number;
            /**
             * Requestedfrom
             * Format: date
             */
            requestedFrom: string;
            /**
             * Requestedto
             * Format: date
             */
            requestedTo: string;
            /** Status */
            status: string;
        };
        /** HistoricalPricePoint */
        HistoricalPricePoint: {
            /** Close */
            close: number | null;
            /** High */
            high: number | null;
            /** Low */
            low: number | null;
            /**
             * Observedat
             * Format: date-time
             */
            observedAt: string;
            /** Open */
            open: number | null;
            /** Qualitystate */
            qualityState: string;
            /** Sourcecode */
            sourceCode: string;
            /**
             * Tradingdate
             * Format: date
             */
            tradingDate: string;
            /** Volume */
            volume: number | null;
        };
        /** HomeDailyFocus */
        HomeDailyFocus: {
            /** Bullets */
            bullets?: string[];
            /** Datadate */
            dataDate: string | null;
            /** Headline */
            headline: string;
            /** Mode */
            mode: string;
            /** Source */
            source: string;
            /** Temporary */
            temporary: boolean;
        };
        /** HomeDataQuality */
        HomeDataQuality: {
            /** Classification */
            classification: string | null;
            /** Missingsections */
            missingSections?: string[];
            /** Notes */
            notes?: string[];
            /** Source */
            source: string;
            /** Status */
            status: string;
            /** Temporarysections */
            temporarySections?: string[];
        };
        /** HomeMarketHealth */
        HomeMarketHealth: {
            /** Advance */
            advance: number | null;
            /** Decline */
            decline: number | null;
            /** Flat */
            flat: number | null;
            /** Market */
            market: string;
            /** Status */
            status: string;
            /** Totalstocks */
            totalStocks: number | null;
            /** Unavailable */
            unavailable: number | null;
        };
        /** HomeMarketOverview */
        HomeMarketOverview: {
            /** Datadate */
            dataDate: string | null;
            /** Datastatus */
            dataStatus: string;
            /** Latestsnapshottime */
            latestSnapshotTime: string | null;
            marketHealth: components["schemas"]["HomeMarketHealth"] | null;
            /** Source */
            source: string;
            /** Trackedstockcount */
            trackedStockCount: number;
            /** Trackedtopiccount */
            trackedTopicCount: number;
            /** Updatedat */
            updatedAt: string | null;
        };
        /** HomeMarketPulseEvent */
        HomeMarketPulseEvent: {
            /** Description */
            description: string;
            /**
             * Eventtime
             * Format: date-time
             */
            eventTime: string;
            /** Eventtype */
            eventType: string;
            /** Severity */
            severity: string;
            /** Source */
            source: string;
            /** Topic */
            topic: string;
            /** Topicslug */
            topicSlug: string;
        };
        /** HomeOpportunityStock */
        HomeOpportunityStock: {
            /** Code */
            code: string;
            /** Datadate */
            dataDate: string | null;
            /** Name */
            name: string;
            /** Reason */
            reason: string | null;
            /** Score */
            score: number | null;
            /** Strategykeys */
            strategyKeys?: string[];
        };
        /** HomeOpportunityTopic */
        HomeOpportunityTopic: {
            /** Currentstate */
            currentState: string | null;
            /** Grade */
            grade: string | null;
            /** Strength */
            strength: number | null;
            /** Summary */
            summary: string;
            /** Temporary */
            temporary: boolean;
            /** Topic */
            topic: string;
            /** Topicslug */
            topicSlug: string;
            /** Validatedstocks */
            validatedStocks?: components["schemas"]["HomeOpportunityStock"][];
        };
        /** HomeResponse */
        HomeResponse: {
            /** Asof */
            asOf: string | null;
            /** Contractversion */
            contractVersion: string;
            /** Coolingtopics */
            coolingTopics?: components["schemas"]["HomeRotationTopic"][];
            dailyFocus: components["schemas"]["HomeDailyFocus"];
            dataQuality: components["schemas"]["HomeDataQuality"];
            /** Generatedat */
            generatedAt: string | null;
            /** Heatingtopics */
            heatingTopics?: components["schemas"]["HomeRotationTopic"][];
            /** Maintopics */
            mainTopics?: components["schemas"]["HomeTopicCard"][];
            marketOverview: components["schemas"]["HomeMarketOverview"];
            /** Marketpulse */
            marketPulse?: components["schemas"]["HomeMarketPulseEvent"][];
            /** Opportunities */
            opportunities?: components["schemas"]["HomeOpportunityTopic"][];
        };
        /** HomeRotationTopic */
        HomeRotationTopic: {
            /** Currentgrade */
            currentGrade: string;
            /** Strengthdelta */
            strengthDelta: number;
            /** Summary */
            summary: string;
            /** Topic */
            topic: string;
            /** Topicslug */
            topicSlug: string;
        };
        /** HomeTopicCard */
        HomeTopicCard: {
            /** Currentstate */
            currentState: string | null;
            /** Datadate */
            dataDate: string | null;
            /** Favorite */
            favorite: boolean;
            /** Grade */
            grade: string | null;
            /** Name */
            name: string;
            /** Slug */
            slug: string;
            /** Stockcount */
            stockCount: number;
            /** Strength */
            strength: number | null;
            /** Summary */
            summary: string;
        };
        /** LiveRunSummary */
        LiveRunSummary: {
            /** Completedat */
            completedAt: string | null;
            /** Id */
            id: string;
            /** Latencyms */
            latencyMs: number | null;
            /** Requestedcount */
            requestedCount: number;
            /**
             * Startedat
             * Format: date-time
             */
            startedAt: string;
            /** Type */
            type: string;
        };
        /** LiveStatusResponse */
        LiveStatusResponse: {
            /** Failurecode */
            failureCode?: string | null;
            /** Failurecount */
            failureCount: number;
            /** Failuremessage */
            failureMessage?: string | null;
            /** Freshnessstate */
            freshnessState: string;
            /** Heartbeatat */
            heartbeatAt: string | null;
            lastRun: components["schemas"]["LiveRunSummary"] | null;
            /** Providerhealth */
            providerHealth?: {
                [key: string]: unknown;
            }[];
            /** Providerstatus */
            providerStatus: string;
            /** Retrycount */
            retryCount: number;
            /**
             * Skippedcount
             * @default 0
             */
            skippedCount: number;
            /** Status */
            status: string;
            /** Successcount */
            successCount: number;
            /** Universecounts */
            universeCounts?: {
                [key: string]: number;
            };
        };
        /** LiveTrackingResponse */
        LiveTrackingResponse: {
            /** Freshnessstate */
            freshnessState: string;
            /** Instrumentcode */
            instrumentCode: string;
            /** Latestclose */
            latestClose: number | null;
            /** Market */
            market: string;
            /** Movingaverage */
            movingAverage: number | null;
            /** Movingaverageperiod */
            movingAveragePeriod: number;
            /** Movingaveragestate */
            movingAverageState: string;
            /** Observationcount */
            observationCount: number;
            /** Observedat */
            observedAt: string | null;
            /** Reason */
            reason: string;
            /** Updatemode */
            updateMode: string;
            /** Updatedat */
            updatedAt: string | null;
        };
        /** OpportunityShadowCard */
        OpportunityShadowCard: {
            /** Asof */
            asOf: string | null;
            /** Confidence */
            confidence: string | null;
            /** Confidencebasis */
            confidenceBasis?: string[];
            /** Datastatus */
            dataStatus: string;
            /** Detail */
            detail?: {
                [key: string]: unknown;
            } | null;
            /** Displaykey */
            displayKey: string;
            /** Displayorder */
            displayOrder: number;
            /** Eligibility */
            eligibility: string;
            /** Entrycontext */
            entryContext?: {
                [key: string]: unknown;
            }[];
            /** Evidencecoverage */
            evidenceCoverage?: {
                [key: string]: unknown;
            };
            /** Exclusioncodes */
            exclusionCodes?: string[];
            /** Exclusionfactors */
            exclusionFactors?: {
                [key: string]: unknown;
            }[];
            /** Explanation */
            explanation?: {
                [key: string]: unknown;
            };
            instrument: components["schemas"]["OpportunityShadowInstrument"];
            /** Instrumentid */
            instrumentId: string;
            /** Labelkey */
            labelKey: string;
            /** Missingevidence */
            missingEvidence?: string[];
            /** Name */
            name: string;
            /** Opportunityid */
            opportunityId: string;
            /** Opportunitykey */
            opportunityKey: string;
            /** Opportunitystate */
            opportunityState: string;
            /** Parameterversion */
            parameterVersion: string;
            /** Policyversion */
            policyVersion: string;
            /** Positivefactors */
            positiveFactors?: {
                [key: string]: unknown;
            }[];
            /** Publicationstatus */
            publicationStatus: string;
            qualification: components["schemas"]["OpportunityShadowQualification"];
            /** Qualificationclass */
            qualificationClass: string;
            /** Qualificationprovenance */
            qualificationProvenance: {
                [key: string]: unknown;
            };
            /** Qualificationstatus */
            qualificationStatus: string;
            /** Rank */
            rank: number;
            /** Rankscore */
            rankScore: number | null;
            /** Rankingprofileversion */
            rankingProfileVersion: string | null;
            /** Rankingstatus */
            rankingStatus: string;
            /** Reasoncodes */
            reasonCodes?: string[];
            /** Riskcontext */
            riskContext?: {
                [key: string]: unknown;
            }[];
            /** Riskfactors */
            riskFactors?: {
                [key: string]: unknown;
            }[];
            /** Sourcedatastatus */
            sourceDataStatus?: string | null;
            /** Status */
            status: string;
            /** Strategyid */
            strategyId: string;
            /** Strategylabelkey */
            strategyLabelKey: string;
            /** Strategytype */
            strategyType: string;
            /** Supportcontext */
            supportContext?: {
                [key: string]: unknown;
            }[];
            /** Symbol */
            symbol: string;
            topic: components["schemas"]["OpportunityShadowTopic"];
            /** Topicgrade */
            topicGrade: string | null;
            /** Topicid */
            topicId: string;
            /** Topiclifecycle */
            topicLifecycle: string | null;
            /** Topicname */
            topicName: string;
            /** Topicstrength */
            topicStrength: number | null;
            /** Waitingfactors */
            waitingFactors?: {
                [key: string]: unknown;
            }[];
        };
        /** OpportunityShadowInstrument */
        OpportunityShadowInstrument: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Symbol */
            symbol: string;
        };
        /** OpportunityShadowQualification */
        OpportunityShadowQualification: {
            /** Class */
            class: string;
            /** Exceptioncandidate */
            exceptionCandidate: boolean;
            /** Parameterversion */
            parameterVersion: string | null;
            /** Policyversion */
            policyVersion: string | null;
            /** Reasoncodes */
            reasonCodes?: string[];
            /** Status */
            status: string;
        };
        /**
         * OpportunityShadowResponse
         * @description Typed, shadow-only Opportunity read contract.
         */
        OpportunityShadowResponse: {
            /** Asof */
            asOf: string | null;
            /** Contractversion */
            contractVersion: string;
            /** Datastatus */
            dataStatus: string;
            /** Opportunities */
            opportunities?: components["schemas"]["OpportunityShadowCard"][];
            opportunity?: components["schemas"]["OpportunityShadowCard"] | null;
            /** Publicationstatus */
            publicationStatus: string;
            /** Query */
            query?: {
                [key: string]: unknown;
            };
            /** Status */
            status: string;
            stock?: components["schemas"]["OpportunityShadowInstrument"] | null;
            /** Strategies */
            strategies?: {
                [key: string]: components["schemas"]["OpportunityShadowStrategySection"];
            };
            topic?: components["schemas"]["OpportunityShadowTopic"] | null;
            /** Topicgrade */
            topicGrade?: string | null;
            /** Topicid */
            topicId?: string | null;
            /** Topiclifecycle */
            topicLifecycle?: string | null;
            /** Topicname */
            topicName?: string | null;
            /** Topicstrength */
            topicStrength?: number | null;
            /** Topics */
            topics?: {
                [key: string]: unknown;
            }[];
        };
        /** OpportunityShadowStrategySection */
        OpportunityShadowStrategySection: {
            /** Backendcandidatecount */
            backendCandidateCount: number;
            /** Backendranking */
            backendRanking?: {
                [key: string]: unknown;
            }[];
            /** Candidatecount */
            candidateCount: number;
            /** Fit */
            fit: string;
            /** Fullrankingretained */
            fullRankingRetained: boolean;
            /** Opportunities */
            opportunities?: components["schemas"]["OpportunityShadowCard"][];
            /** Presentationcap */
            presentationCap: number | null;
            /** Presentedcount */
            presentedCount: number;
            /** Strategyid */
            strategyId: string;
            /** Strategylabelkey */
            strategyLabelKey: string;
            /** Strategytype */
            strategyType: string;
        };
        /** OpportunityShadowTopic */
        OpportunityShadowTopic: {
            /** Grade */
            grade: string | null;
            /** Id */
            id: string;
            /** Lifecycle */
            lifecycle: string | null;
            /** Name */
            name: string;
            /** Strength */
            strength: number | null;
        };
        /** Page[CandidateResponse] */
        Page_CandidateResponse_: {
            /** Items */
            items: components["schemas"]["CandidateResponse"][];
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Total */
            total: number;
        };
        /** Page[LiveTrackingResponse] */
        Page_LiveTrackingResponse_: {
            /** Items */
            items: components["schemas"]["LiveTrackingResponse"][];
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Total */
            total: number;
        };
        /** Page[StockSummary] */
        Page_StockSummary_: {
            /** Items */
            items: components["schemas"]["StockSummary"][];
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Total */
            total: number;
        };
        /** Page[StrategyPerformanceResponse] */
        Page_StrategyPerformanceResponse_: {
            /** Items */
            items: components["schemas"]["StrategyPerformanceResponse"][];
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Total */
            total: number;
        };
        /** Page[StrategyResponse] */
        Page_StrategyResponse_: {
            /** Items */
            items: components["schemas"]["StrategyResponse"][];
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Total */
            total: number;
        };
        /** Page[TopicRotationResponse] */
        Page_TopicRotationResponse_: {
            /** Items */
            items: components["schemas"]["TopicRotationResponse"][];
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Total */
            total: number;
        };
        /** Page[TopicSummary] */
        Page_TopicSummary_: {
            /** Items */
            items: components["schemas"]["TopicSummary"][];
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Total */
            total: number;
        };
        /** RecommendationComponent */
        RecommendationComponent: {
            /** Name */
            name: string;
            /** Value */
            value: number | null;
        };
        /** RecommendationItemResponse */
        RecommendationItemResponse: {
            /** Candidateid */
            candidateId: string;
            /** Evidence */
            evidence?: string[];
            /** Label */
            label: string;
            /** Reason */
            reason: string;
            /** Status */
            status: string;
            topicContext: components["schemas"]["RecommendationTopicContext"] | null;
            /** Topicid */
            topicId: string;
        };
        /** RecommendationResponse */
        RecommendationResponse: {
            /** Asof */
            asOf: string | null;
            /** Contractversion */
            contractVersion: string;
            /** Items */
            items?: components["schemas"]["RecommendationItemResponse"][];
            /** Status */
            status: string;
        };
        /** RecommendationTopicContext */
        RecommendationTopicContext: {
            /** Aggregationversion */
            aggregationVersion: string | null;
            /** Asof */
            asOf: string | null;
            /** Components */
            components?: components["schemas"]["RecommendationComponent"][];
            /** Confidence */
            confidence: number | null;
            /** Eligibility */
            eligibility: string | null;
            /** Evidencereference */
            evidenceReference?: string[];
            /** Featureruntimeversion */
            featureRuntimeVersion: string | null;
            /** Featuresetversion */
            featureSetVersion: string | null;
            /** Grade */
            grade: string | null;
            /** Policyid */
            policyId: string | null;
            /** Policyversion */
            policyVersion: string | null;
            /** Score */
            score: number | null;
            /** Scorerruntimeversion */
            scorerRuntimeVersion: string | null;
        };
        /** SnapshotResponse */
        SnapshotResponse: {
            /** Classification */
            classification: string;
            /**
             * Datadate
             * Format: date
             */
            dataDate: string;
            /**
             * Generatedat
             * Format: date-time
             */
            generatedAt: string;
            /** Snapshotversion */
            snapshotVersion: string;
        } & {
            [key: string]: unknown;
        };
        /** StockReadModel */
        StockReadModel: {
            /** Active */
            active: boolean;
            /** Changepct */
            changePct: number | null;
            /** Code */
            code: string;
            /** Datafreshness */
            dataFreshness: string;
            /** Enabled */
            enabled: boolean;
            /** Exchange */
            exchange: string | null;
            /** Favorite */
            favorite: {
                [key: string]: unknown;
            } | null;
            /** Historycoverage */
            historyCoverage?: {
                [key: string]: unknown;
            };
            /** Institutionflows */
            institutionFlows: {
                [key: string]: unknown;
            } | null;
            /** Instrumentid */
            instrumentId: string;
            /** Listing */
            listing: string | null;
            /** Ma20State */
            ma20State: string | null;
            /** Ma60State */
            ma60State: string | null;
            /** Maintopic */
            mainTopic: {
                [key: string]: unknown;
            } | null;
            /** Market */
            market: string;
            /** Marketstatus */
            marketStatus: string;
            /** Name */
            name: string | null;
            /** Observedat */
            observedAt: string | null;
            /** Opportunity */
            opportunity: {
                [key: string]: unknown;
            } | null;
            /** Price */
            price: number | null;
            /** Retrievedat */
            retrievedAt: string | null;
            /** Summary */
            summary: string | null;
            /** Symbol */
            symbol: string;
            technicalEvidence: components["schemas"]["StockTechnicalEvidence"] | null;
            /** Topicrelations */
            topicRelations?: components["schemas"]["StockTopicRelationRead"][];
            /** Trackingmode */
            trackingMode: string;
            /** Trackingreason */
            trackingReason: string | null;
            /** Updatemode */
            updateMode: string;
            /** Volume */
            volume: number | null;
        };
        /** StockReadModelPage */
        StockReadModelPage: {
            /** Items */
            items: components["schemas"]["StockReadModel"][];
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Query */
            query: {
                [key: string]: unknown;
            };
            /** Total */
            total: number;
            /** Universe */
            universe: {
                [key: string]: number;
            };
        };
        /** StockResponse */
        StockResponse: {
            /** Active */
            active: boolean;
            /** Changepct */
            changePct: number | null;
            /** Chipscore */
            chipScore: number | null;
            /** Code */
            code: string;
            /** Datadate */
            dataDate: string | null;
            /** Datafreshness */
            dataFreshness: string | null;
            /** Industry */
            industry: string | null;
            /** Ma20 */
            ma20: number | null;
            /** Ma5 */
            ma5: number | null;
            /** Market */
            market: string;
            /** Name */
            name: string;
            /** Price */
            price: number | null;
            /** Rs20 */
            rs20: number | null;
            /** Technicalstate */
            technicalState: string | null;
            /**
             * Topics
             * @default []
             */
            topics: components["schemas"]["TopicReference"][];
            /** Volume */
            volume: number | null;
        };
        /** StockSummary */
        StockSummary: {
            /** Active */
            active: boolean;
            /** Changepct */
            changePct: number | null;
            /** Code */
            code: string;
            /** Datadate */
            dataDate: string | null;
            /** Datafreshness */
            dataFreshness: string | null;
            /** Industry */
            industry: string | null;
            /** Market */
            market: string;
            /** Name */
            name: string;
            /** Price */
            price: number | null;
            /** Technicalstate */
            technicalState: string | null;
            /** Volume */
            volume: number | null;
        };
        /** StockTechnicalEvidence */
        StockTechnicalEvidence: {
            /** Above20Ma */
            above20MA: boolean | null;
            /** Above60Ma */
            above60MA: boolean | null;
            /** Breakoutstate */
            breakoutState: string | null;
            /** Ma20 */
            ma20: number | null;
            /** Ma60 */
            ma60: number | null;
            /** Technicalstate */
            technicalState: string | null;
        };
        /** StockTopicRelationRead */
        StockTopicRelationRead: {
            /** Relationtype */
            relationType: string;
            /** Relationweight */
            relationWeight: number | null;
            /** Topicid */
            topicId: string;
            /** Topicname */
            topicName: string;
            /** Topicrole */
            topicRole: string | null;
            /** Topicslug */
            topicSlug: string;
        };
        /** StrategyPerformanceResponse */
        StrategyPerformanceResponse: {
            /** Averagereturnpct */
            averageReturnPct: number | null;
            /** Candidatecount */
            candidateCount: number;
            /**
             * Datadate
             * Format: date
             */
            dataDate: string;
            /** Horizon */
            horizon: string;
            /** Modelversion */
            modelVersion: string;
            /** Reason */
            reason: string | null;
            /** Runstatus */
            runStatus: string;
            /** Samplecount */
            sampleCount: number | null;
            /** Selectedcount */
            selectedCount: number;
            /** Status */
            status: string;
            /** Strategykey */
            strategyKey: string;
            /** Strategyname */
            strategyName: string;
            /** Winratepct */
            winRatePct: number | null;
        };
        /** StrategyResponse */
        StrategyResponse: {
            /** Candidatecount */
            candidateCount: number;
            /**
             * Datadate
             * Format: date
             */
            dataDate: string;
            /** Modelversion */
            modelVersion: string;
            /** Name */
            name: string;
            /** Selectedcount */
            selectedCount: number;
            /** Status */
            status: string;
            /** Strategykey */
            strategyKey: string;
        };
        /** TopicConstituentRead */
        TopicConstituentRead: {
            /** Changepct */
            changePct: number | null;
            /** Code */
            code: string;
            /** Freshness */
            freshness: string;
            /** Instrumentid */
            instrumentId: string;
            /** Name */
            name: string | null;
            /** Observedat */
            observedAt: string | null;
            /** Price */
            price: number | null;
            /** Relationweight */
            relationWeight: number | null;
            /** Relativetopicstate */
            relativeTopicState: string | null;
            /** Role */
            role: string | null;
            /** Symbol */
            symbol: string;
            /** Technicalstate */
            technicalState: string | null;
            /** Updatemode */
            updateMode: string;
        };
        /** TopicIntelligenceComponent */
        TopicIntelligenceComponent: {
            /** Name */
            name: string;
            /** Value */
            value: number | null;
        };
        /** TopicIntelligenceEvidence */
        TopicIntelligenceEvidence: {
            /** Aggregatestatus */
            aggregateStatus: string;
            /** Features */
            features: components["schemas"]["TopicIntelligenceFeatureEvidence"][];
            quality: components["schemas"]["TopicIntelligenceQuality"];
            /** Qualityflags */
            qualityFlags: string[];
        };
        /** TopicIntelligenceFeatureEvidence */
        TopicIntelligenceFeatureEvidence: {
            /** Coverage */
            coverage: number | null;
            /** Metadata */
            metadata: {
                [key: string]: unknown;
            };
            /** Name */
            name: string;
            /** Qualityflags */
            qualityFlags: string[];
            /** Status */
            status: string;
            /** Value */
            value: unknown | null;
            /** Version */
            version: string;
        };
        /** TopicIntelligencePolicy */
        TopicIntelligencePolicy: {
            /** Policyid */
            policyId: string;
            /** Policyversion */
            policyVersion: string;
        };
        /** TopicIntelligenceQuality */
        TopicIntelligenceQuality: {
            /** Coveragemean */
            coverageMean: number | null;
            /** Coveragemin */
            coverageMin: number | null;
            /** Insufficientfeaturecount */
            insufficientFeatureCount: number;
            /** Invalidfeaturecount */
            invalidFeatureCount: number;
            /** Readyfeaturecount */
            readyFeatureCount: number;
        };
        /** TopicIntelligenceResponse */
        TopicIntelligenceResponse: {
            /**
             * Asof
             * Format: date
             */
            asOf: string;
            /** Contractversion */
            contractVersion: string;
            /** Mode */
            mode: string;
            policy: components["schemas"]["TopicIntelligencePolicy"];
            /** Status */
            status: string;
            /** Topics */
            topics: components["schemas"]["TopicIntelligenceTopic"][];
            versions: components["schemas"]["TopicIntelligenceVersions"];
        };
        /** TopicIntelligenceTopic */
        TopicIntelligenceTopic: {
            /** Components */
            components: components["schemas"]["TopicIntelligenceComponent"][];
            /** Confidence */
            confidence: number | null;
            /** Eligibility */
            eligibility: string;
            evidence: components["schemas"]["TopicIntelligenceEvidence"];
            /** Grade */
            grade: string | null;
            /** Score */
            score: number | null;
            /** Status */
            status: string;
            /** Strength */
            strength: string | null;
            /** Topicid */
            topicId: string;
        };
        /** TopicIntelligenceVersions */
        TopicIntelligenceVersions: {
            /** Aggregation */
            aggregation: string;
            /** Featureruntime */
            featureRuntime: string;
            /** Featureset */
            featureSet: string;
            /** Scorerruntime */
            scorerRuntime: string;
        };
        /** TopicLifecycleRead */
        TopicLifecycleRead: {
            /** Candidatestage */
            candidateStage?: string | null;
            /** Confidence */
            confidence?: {
                [key: string]: unknown;
            };
            /** Currentstage */
            currentStage: string | null;
            /** Currentstageenteredat */
            currentStageEnteredAt: string | null;
            /** Currentstagetradingdays */
            currentStageTradingDays: number | null;
            /** Datastatus */
            dataStatus: string;
            /** Evaluationdate */
            evaluationDate?: string | null;
            /** Evidence */
            evidence?: {
                [key: string]: unknown;
            };
            /** History */
            history?: components["schemas"]["TopicLifecycleSegmentRead"][];
            /** Policyversion */
            policyVersion?: string | null;
            /** Previousstage */
            previousStage?: string | null;
            /** Transitiondecision */
            transitionDecision?: string | null;
            /** Transitionreason */
            transitionReason?: string | null;
        };
        /** TopicLifecycleSegmentRead */
        TopicLifecycleSegmentRead: {
            /** Current */
            current: boolean;
            /** Enteredat */
            enteredAt: string | null;
            /** Exitedat */
            exitedAt: string | null;
            /** Stage */
            stage: string;
            /** Tradingdays */
            tradingDays: number | null;
        };
        /** TopicReadModel */
        TopicReadModel: {
            /** Constituentcount */
            constituentCount: number;
            /** Constituents */
            constituents?: components["schemas"]["TopicConstituentRead"][];
            /** Coveragepct */
            coveragePct: number | null;
            /** Datadate */
            dataDate: string | null;
            /** Direction */
            direction: string | null;
            /** Enabled */
            enabled: boolean;
            /** Grade */
            grade: string | null;
            /** Groupname */
            groupName: string | null;
            lifecycle: components["schemas"]["TopicLifecycleRead"];
            /** Name */
            name: string;
            /** Readablestate */
            readableState: string;
            /** Score */
            score: number | null;
            /** Slug */
            slug: string;
            /** Status */
            status?: components["schemas"]["TopicStatusRead"][];
            /** Strengthstate */
            strengthState: string | null;
            /** Topicid */
            topicId: string;
            /** Topictype */
            topicType: string;
        };
        /** TopicReadModelPage */
        TopicReadModelPage: {
            /** Items */
            items: components["schemas"]["TopicReadModel"][];
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Query */
            query: {
                [key: string]: unknown;
            };
            /** Total */
            total: number;
        };
        /** TopicReference */
        TopicReference: {
            /** Name */
            name: string;
            /** Relationtype */
            relationType: string;
            /** Slug */
            slug: string;
            /** Weight */
            weight: number | null;
        };
        /** TopicResponse */
        TopicResponse: {
            /** Constituentcount */
            constituentCount: number;
            /**
             * Constituents
             * @default []
             */
            constituents: components["schemas"]["Constituent"][];
            /** Coveragepct */
            coveragePct: number | null;
            /** Datadate */
            dataDate: string | null;
            /** Enabled */
            enabled: boolean;
            /** Grade */
            grade: string | null;
            /** Groupname */
            groupName: string | null;
            /** Name */
            name: string;
            /** Score */
            score: number | null;
            /** Slug */
            slug: string;
            /** Strengthstate */
            strengthState: string | null;
            /** Topictype */
            topicType: string;
        };
        /** TopicRotationResponse */
        TopicRotationResponse: {
            /** Change */
            change: number | null;
            /** Days */
            days: number;
            /** Groupname */
            groupName: string | null;
            /** Latestcoveragepct */
            latestCoveragePct: number | null;
            /**
             * Latestdate
             * Format: date
             */
            latestDate: string;
            /** Latestgrade */
            latestGrade: string | null;
            /** Latestscore */
            latestScore: number | null;
            /** Lateststrengthstate */
            latestStrengthState: string | null;
            /** Pointcount */
            pointCount: number;
            /** Topicname */
            topicName: string;
            /** Topicslug */
            topicSlug: string;
        };
        /** TopicSnapshotPage */
        TopicSnapshotPage: {
            /** Items */
            items: components["schemas"]["TopicSnapshotResponse"][];
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Query */
            query: {
                [key: string]: unknown;
            };
            /** Total */
            total: number;
        };
        /** TopicSnapshotResponse */
        TopicSnapshotResponse: {
            /** Averagechange */
            averageChange: number | null;
            /** Calculationversion */
            calculationVersion: string;
            /** Coveragepct */
            coveragePct: number | null;
            /** Datastatus */
            dataStatus: string;
            /** Marketgrade */
            marketGrade: string | null;
            /** Observedstockcount */
            observedStockCount: number;
            /** Parenttopic */
            parentTopic: string | null;
            /** Scorestatus */
            scoreStatus: string;
            /**
             * Snapshotdate
             * Format: date
             */
            snapshotDate: string;
            /** Stockcount */
            stockCount: number;
            /** Strongstockcount */
            strongStockCount: number;
            /** Topicdirection */
            topicDirection: string;
            /** Topicid */
            topicId: string;
            /** Topicname */
            topicName: string;
            /** Topicscore */
            topicScore: number | null;
            /** Topicslug */
            topicSlug: string;
            /**
             * Updatedat
             * Format: date-time
             */
            updatedAt: string;
            /** Weakstockcount */
            weakStockCount: number;
        };
        /** TopicStatusRead */
        TopicStatusRead: {
            /** Evidence */
            evidence?: {
                [key: string]: unknown;
            };
            /** Key */
            key: string;
            /** State */
            state: string | null;
        };
        /** TopicSummary */
        TopicSummary: {
            /** Constituentcount */
            constituentCount: number;
            /** Coveragepct */
            coveragePct: number | null;
            /** Datadate */
            dataDate: string | null;
            /** Enabled */
            enabled: boolean;
            /** Grade */
            grade: string | null;
            /** Groupname */
            groupName: string | null;
            /** Name */
            name: string;
            /** Score */
            score: number | null;
            /** Slug */
            slug: string;
            /** Strengthstate */
            strengthState: string | null;
            /** Topictype */
            topicType: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    dashboard_api_v1_admin_dashboard_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    imports_api_v1_admin_imports_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    import_detail_api_v1_admin_imports__run_id__get: {
        parameters: {
            query?: {
                record_limit?: number;
                record_offset?: number;
                outcome?: string | null;
                entity?: string | null;
            };
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    instruments_api_v1_admin_instruments_get: {
        parameters: {
            query?: {
                q?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    instrument_detail_api_v1_admin_instruments__instrument_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                instrument_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    markets_api_v1_admin_markets_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    relations_api_v1_admin_relations_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    schema_api_v1_admin_schema_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    topics_api_v1_admin_topics_get: {
        parameters: {
            query?: {
                q?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    topic_detail_api_v1_admin_topics__topic_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                topic_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    performance_api_v1_analytics_strategy_performance_get: {
        parameters: {
            query?: {
                strategy_key?: string | null;
                horizon?: string | null;
                data_date?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_StrategyPerformanceResponse_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rotation_api_v1_analytics_topic_rotation_get: {
        parameters: {
            query?: {
                days?: number;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_TopicRotationResponse_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    api_data_status_api_v1_meta_data_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataStatus"];
                };
            };
        };
    };
    configuration_api_v1_operations_live_configuration_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    status_api_v1_operations_live_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LiveStatusResponse"];
                };
            };
        };
    };
    tracking_api_v1_operations_live_tracking_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_LiveTrackingResponse_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_shadow_opportunities_api_v1_opportunities_shadow_get: {
        parameters: {
            query?: {
                strategy?: string | null;
                state?: string | null;
                topicId?: string | null;
                instrumentId?: string | null;
                grade?: string | null;
                lifecycle?: string | null;
                limit?: number;
                page?: number;
                cursor?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OpportunityShadowResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    shadow_opportunity_detail_api_v1_opportunities_shadow__opportunity_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                opportunity_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OpportunityShadowResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    latest_recommendations_api_v1_recommendations_latest_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecommendationResponse"];
                };
            };
            /** @description No approved Recommendation provider is configured */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    snapshot_latest_api_v1_snapshot_latest_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SnapshotResponse"];
                };
            };
        };
    };
    stocks_api_v1_stocks_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_StockSummary_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stock_api_v1_stocks__code__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StockResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stock_price_history_api_v1_stocks__code__price_history_get: {
        parameters: {
            query: {
                from: string;
                to: string;
                market?: string | null;
                limit?: number;
            };
            header?: never;
            path: {
                code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HistoricalPriceHistoryResponse"];
                };
            };
            /** @description Ambiguous instrument identity */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stock_shadow_opportunities_api_v1_stocks__instrument_id__opportunities_shadow_get: {
        parameters: {
            query?: {
                strategy?: string | null;
                state?: string | null;
                topicId?: string | null;
                grade?: string | null;
                lifecycle?: string | null;
                limit?: number;
                page?: number;
                cursor?: string | null;
            };
            header?: never;
            path: {
                instrument_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OpportunityShadowResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    strategies_api_v1_strategies_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_StrategyResponse_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    candidates_api_v1_strategies__key__candidates_get: {
        parameters: {
            query?: {
                data_date?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path: {
                key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_CandidateResponse_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    latest_topic_intelligence_api_v1_topic_intelligence_latest_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TopicIntelligenceResponse"];
                };
            };
            /** @description Configured provider returned invalid evidence */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No approved runtime provider is configured */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    topics_api_v1_topics_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_TopicSummary_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    topic_api_v1_topics__slug__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TopicResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    topic_shadow_opportunities_api_v1_topics__topic_id__opportunities_shadow_get: {
        parameters: {
            query?: {
                strategy?: string | null;
                state?: string | null;
                grade?: string | null;
                lifecycle?: string | null;
                limit?: number;
                page?: number;
                cursor?: string | null;
            };
            header?: never;
            path: {
                topic_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OpportunityShadowResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    home_api_v2_home_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HomeResponse"];
                };
            };
        };
    };
    stocks_api_v2_stocks_get: {
        parameters: {
            query?: {
                market?: string | null;
                /** @description Formal topic slug */
                topic?: string | null;
                updateMode?: string | null;
                sort?: string;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StockReadModelPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stock_api_v2_stocks__symbol__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                symbol: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StockReadModel"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_topic_snapshots_api_v2_topic_snapshots_get: {
        parameters: {
            query?: {
                date?: string | null;
                latest?: boolean;
                /** @description Topic slug */
                topic?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TopicSnapshotPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    topics_api_v2_topics_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TopicReadModelPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    topic_api_v2_topics__slug__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TopicReadModel"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    readyz_readyz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
            /** @description Database unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
