/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/analytics/strategy-performance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Performance */
        get: operations["performance_api_v1_analytics_strategy_performance_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analytics/topic-rotation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Rotation */
        get: operations["rotation_api_v1_analytics_topic_rotation_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/meta/data-status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Api Data Status */
        get: operations["api_data_status_api_v1_meta_data_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/snapshot/latest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Snapshot Latest */
        get: operations["snapshot_latest_api_v1_snapshot_latest_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stocks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stocks */
        get: operations["stocks_api_v1_stocks_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stocks/{code}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stock */
        get: operations["stock_api_v1_stocks__code__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/strategies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Strategies */
        get: operations["strategies_api_v1_strategies_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/strategies/{key}/candidates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Candidates */
        get: operations["candidates_api_v1_strategies__key__candidates_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/topics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Topics */
        get: operations["topics_api_v1_topics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/topics/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Topic */
        get: operations["topic_api_v1_topics__slug__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Healthz */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Readyz */
        get: operations["readyz_readyz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** CandidateResponse */
        CandidateResponse: {
            /** Code */
            code: string;
            /**
             * Datadate
             * Format: date
             */
            dataDate: string;
            /** Invalidationprice */
            invalidationPrice: number | null;
            /** Modelversion */
            modelVersion: string;
            /** Name */
            name: string;
            /** Price */
            price: number | null;
            /** Rank */
            rank: number;
            /** Reason */
            reason: string | null;
            /** Score */
            score: number | null;
            /** Selected */
            selected: boolean;
            /** Strategykey */
            strategyKey: string;
            /** Supportprice */
            supportPrice: number | null;
            /** Triggerprice */
            triggerPrice: number | null;
        };
        /** Constituent */
        Constituent: {
            /** Code */
            code: string;
            /** Name */
            name: string;
            /** Relationtype */
            relationType: string;
            /** Weight */
            weight: number | null;
        };
        /** DataStatus */
        DataStatus: {
            /** Agedays */
            ageDays: number;
            /** Bundlehash */
            bundleHash: string;
            /** Bundleversion */
            bundleVersion: string;
            /** Classification */
            classification: string;
            /**
             * Completedat
             * Format: date-time
             */
            completedAt: string;
            /** Contractversion */
            contractVersion: string;
            /**
             * Datadate
             * Format: date
             */
            dataDate: string;
            /** Freshness */
            freshness: string;
            /**
             * Generatedat
             * Format: date-time
             */
            generatedAt: string;
            /** Rowcounts */
            rowCounts: {
                [key: string]: number;
            };
            /** Sourcekind */
            sourceKind: string;
            /** Sourcename */
            sourceName: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Status */
            status: string;
        };
        /** Page[CandidateResponse] */
        Page_CandidateResponse_: {
            /** Items */
            items: components["schemas"]["CandidateResponse"][];
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Total */
            total: number;
        };
        /** Page[StockSummary] */
        Page_StockSummary_: {
            /** Items */
            items: components["schemas"]["StockSummary"][];
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Total */
            total: number;
        };
        /** Page[StrategyPerformanceResponse] */
        Page_StrategyPerformanceResponse_: {
            /** Items */
            items: components["schemas"]["StrategyPerformanceResponse"][];
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Total */
            total: number;
        };
        /** Page[StrategyResponse] */
        Page_StrategyResponse_: {
            /** Items */
            items: components["schemas"]["StrategyResponse"][];
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Total */
            total: number;
        };
        /** Page[TopicRotationResponse] */
        Page_TopicRotationResponse_: {
            /** Items */
            items: components["schemas"]["TopicRotationResponse"][];
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Total */
            total: number;
        };
        /** Page[TopicSummary] */
        Page_TopicSummary_: {
            /** Items */
            items: components["schemas"]["TopicSummary"][];
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Total */
            total: number;
        };
        /** SnapshotResponse */
        SnapshotResponse: {
            /**
             * Datadate
             * Format: date
             */
            dataDate: string;
            /**
             * Generatedat
             * Format: date-time
             */
            generatedAt: string;
            /** Snapshotversion */
            snapshotVersion: string;
        } & {
            [key: string]: unknown;
        };
        /** StockResponse */
        StockResponse: {
            /** Active */
            active: boolean;
            /** Changepct */
            changePct: number | null;
            /** Chipscore */
            chipScore: number | null;
            /** Code */
            code: string;
            /** Datadate */
            dataDate: string | null;
            /** Datafreshness */
            dataFreshness: string | null;
            /** Industry */
            industry: string | null;
            /** Ma20 */
            ma20: number | null;
            /** Ma5 */
            ma5: number | null;
            /** Market */
            market: string;
            /** Name */
            name: string;
            /** Price */
            price: number | null;
            /** Rs20 */
            rs20: number | null;
            /** Technicalstate */
            technicalState: string | null;
            /**
             * Topics
             * @default []
             */
            topics: components["schemas"]["TopicReference"][];
            /** Volume */
            volume: number | null;
        };
        /** StockSummary */
        StockSummary: {
            /** Active */
            active: boolean;
            /** Changepct */
            changePct: number | null;
            /** Code */
            code: string;
            /** Datadate */
            dataDate: string | null;
            /** Datafreshness */
            dataFreshness: string | null;
            /** Industry */
            industry: string | null;
            /** Market */
            market: string;
            /** Name */
            name: string;
            /** Price */
            price: number | null;
            /** Technicalstate */
            technicalState: string | null;
            /** Volume */
            volume: number | null;
        };
        /** StrategyPerformanceResponse */
        StrategyPerformanceResponse: {
            /** Averagereturnpct */
            averageReturnPct: number | null;
            /** Candidatecount */
            candidateCount: number;
            /**
             * Datadate
             * Format: date
             */
            dataDate: string;
            /** Horizon */
            horizon: string;
            /** Modelversion */
            modelVersion: string;
            /** Reason */
            reason: string | null;
            /** Runstatus */
            runStatus: string;
            /** Samplecount */
            sampleCount: number | null;
            /** Selectedcount */
            selectedCount: number;
            /** Status */
            status: string;
            /** Strategykey */
            strategyKey: string;
            /** Strategyname */
            strategyName: string;
            /** Winratepct */
            winRatePct: number | null;
        };
        /** StrategyResponse */
        StrategyResponse: {
            /** Candidatecount */
            candidateCount: number;
            /**
             * Datadate
             * Format: date
             */
            dataDate: string;
            /** Modelversion */
            modelVersion: string;
            /** Name */
            name: string;
            /** Selectedcount */
            selectedCount: number;
            /** Status */
            status: string;
            /** Strategykey */
            strategyKey: string;
        };
        /** TopicReference */
        TopicReference: {
            /** Name */
            name: string;
            /** Relationtype */
            relationType: string;
            /** Slug */
            slug: string;
            /** Weight */
            weight: number | null;
        };
        /** TopicResponse */
        TopicResponse: {
            /** Constituentcount */
            constituentCount: number;
            /**
             * Constituents
             * @default []
             */
            constituents: components["schemas"]["Constituent"][];
            /** Coveragepct */
            coveragePct: number | null;
            /** Datadate */
            dataDate: string | null;
            /** Enabled */
            enabled: boolean;
            /** Grade */
            grade: string | null;
            /** Groupname */
            groupName: string | null;
            /** Name */
            name: string;
            /** Score */
            score: number | null;
            /** Slug */
            slug: string;
            /** Strengthstate */
            strengthState: string | null;
            /** Topictype */
            topicType: string;
        };
        /** TopicRotationResponse */
        TopicRotationResponse: {
            /** Change */
            change: number | null;
            /** Days */
            days: number;
            /** Groupname */
            groupName: string | null;
            /** Latestcoveragepct */
            latestCoveragePct: number | null;
            /**
             * Latestdate
             * Format: date
             */
            latestDate: string;
            /** Latestgrade */
            latestGrade: string | null;
            /** Latestscore */
            latestScore: number | null;
            /** Lateststrengthstate */
            latestStrengthState: string | null;
            /** Pointcount */
            pointCount: number;
            /** Topicname */
            topicName: string;
            /** Topicslug */
            topicSlug: string;
        };
        /** TopicSummary */
        TopicSummary: {
            /** Constituentcount */
            constituentCount: number;
            /** Coveragepct */
            coveragePct: number | null;
            /** Datadate */
            dataDate: string | null;
            /** Enabled */
            enabled: boolean;
            /** Grade */
            grade: string | null;
            /** Groupname */
            groupName: string | null;
            /** Name */
            name: string;
            /** Score */
            score: number | null;
            /** Slug */
            slug: string;
            /** Strengthstate */
            strengthState: string | null;
            /** Topictype */
            topicType: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    performance_api_v1_analytics_strategy_performance_get: {
        parameters: {
            query?: {
                strategy_key?: string | null;
                horizon?: string | null;
                data_date?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_StrategyPerformanceResponse_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rotation_api_v1_analytics_topic_rotation_get: {
        parameters: {
            query?: {
                days?: number;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_TopicRotationResponse_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    api_data_status_api_v1_meta_data_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataStatus"];
                };
            };
        };
    };
    snapshot_latest_api_v1_snapshot_latest_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SnapshotResponse"];
                };
            };
        };
    };
    stocks_api_v1_stocks_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_StockSummary_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stock_api_v1_stocks__code__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StockResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    strategies_api_v1_strategies_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_StrategyResponse_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    candidates_api_v1_strategies__key__candidates_get: {
        parameters: {
            query?: {
                data_date?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path: {
                key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_CandidateResponse_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    topics_api_v1_topics_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_TopicSummary_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    topic_api_v1_topics__slug__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TopicResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    readyz_readyz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
            /** @description Database unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
